### ISSUE TITLE
No menu spawn

### ISSUE THREAD

**Issue by frenchy77700** [BossManNz/esx_vehicleTeleportPads#1]
Hello ,

I am wrighting to you today to say i am having isues with the script , i have tried multiple was to try and get it working but with no luck , i first placed the script as it is found the markers went onto the makers and nothing , tried changing the tp areas thinking they where wronley placed went back onto the spawn still nothing , tried changing a bit of code in the config still nothing ! I even stoped mello trainer thinking it was that that was blocking it , I get the markers but no menu to teleport , any ideas?

**Comment by BossManNz** [comment]
Can you send me your config, please.

**Comment by frenchy77700** [comment]
witch config do you need ? Config .Lua ? if so i changed everything back to normal seiing nothing has changed

**Comment by BossManNz** [comment]
Hi mate - yes, in fact if you could send me the entire folder as it is right now. I have re-testing the script on a base ESX Framework server and it works fine. 

You are running ESX, right?

**Comment by frenchy77700** [comment]
Hey bossMan sorry for the long delay my pc broke down and ect ect ... you know the dril . Just to say i have managed to get te script working nicley now i have the issue where i would like to teleport under the map ie: Big garage but i alwais end up spawning way above the actual spawn point . I have looked client side and config but no lucky alwais spawn in the same area :( any ideas?
